const dollars=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2});
const compactDollars=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',notation:'compact',maximumFractionDigits:2});
const pct=new Intl.NumberFormat('en-US',{style:'percent',maximumFractionDigits:1});
const scenarios=[{key:'bear',label:'Bear',color:'#b44747'},{key:'base',label:'Base',color:'#c79022'},{key:'bull',label:'Bull',color:'#12805c'}];
const sample={ticker:'TSLA',currentPrice:175,revenue:97000,shares:3180,eps:2.75,years:7,bearGrowth:6,bearMargin:7,bearPe:24,bearDilution:1.5,baseGrowth:13,baseMargin:11,basePe:36,baseDilution:.5,bullGrowth:22,bullMargin:16,bullPe:55,bullDilution:-.5};
const fields=['ticker','currentPrice','revenue','shares','eps','years','bearGrowth','bearMargin','bearPe','bearDilution','baseGrowth','baseMargin','basePe','baseDilution','bullGrowth','bullMargin','bullPe','bullDilution'];
let lastProjection=null;const el=id=>document.getElementById(id);const numberValue=id=>Number(el(id).value)||0;
function readProjectionInputs(){return{ticker:el('ticker').value.trim().toUpperCase()||'STOCK',currentPrice:numberValue('currentPrice'),revenue:numberValue('revenue'),shares:numberValue('shares'),eps:numberValue('eps'),years:Math.max(1,Math.min(15,numberValue('years'))),cases:Object.fromEntries(scenarios.map(s=>[s.key,{growth:numberValue(`${s.key}Growth`)/100,margin:numberValue(`${s.key}Margin`)/100,pe:numberValue(`${s.key}Pe`),dilution:numberValue(`${s.key}Dilution`)/100}]))}}
function calculateProjection(input){return{input,cases:scenarios.map(s=>{const a=input.cases[s.key],yearly=[];for(let year=0;year<=input.years;year++){const revenue=input.revenue*Math.pow(1+a.growth,year),shares=input.shares*Math.pow(1+a.dilution,year),netIncome=revenue*a.margin,eps=shares>0?netIncome/shares:0,price=eps*a.pe;yearly.push({year,revenue,shares,netIncome,eps,price,returnMultiple:input.currentPrice>0?price/input.currentPrice:0})}const terminal=yearly[yearly.length-1],cagr=input.currentPrice>0?Math.pow(terminal.price/input.currentPrice,1/input.years)-1:0;return{...s,assumptions:a,yearly,terminal,cagr}})}}
function renderProjection(result){lastProjection=result;el('projectionCards').innerHTML=result.cases.map(i=>`<article class="metric-card"><span>${i.label} case</span><strong>${dollars.format(i.terminal.price)}</strong><p>${pct.format(i.cagr)} annualized, ${i.terminal.returnMultiple.toFixed(2)}x return</p></article>`).join('');const base=result.cases.find(i=>i.key==='base');el('projectionDetails').innerHTML=[['Terminal revenue',compactDollars.format(base.terminal.revenue*1e6)],['Terminal net income',compactDollars.format(base.terminal.netIncome*1e6)],['Terminal EPS',dollars.format(base.terminal.eps)],['Terminal shares',`${base.terminal.shares.toFixed(0)}M`]].map(([l,v])=>`<article class="detail-card"><span>${l}</span><strong>${v}</strong></article>`).join('');drawLineChart(el('projectionChart'),result.cases,'price')}
const formatMaybe=(value,formatter=dollars)=>value===null||value===undefined||value===''?'N/A':Number.isFinite(Number(value))?formatter.format(Number(value)):'N/A';const setDataStatus=m=>el('dataStatus').textContent=m;
async function fetchStockData(symbol){const clean=String(symbol||'').trim().toUpperCase();if(!clean)throw new Error('Enter a ticker first.');const r=await fetch(`/api/stock/${encodeURIComponent(clean)}`),data=await r.json();if(!r.ok)throw new Error(data.error||'Could not fetch stock data.');return data}
function renderStockDataCard(data){const asOf=data.timestamp?new Date(data.timestamp).toLocaleString():'latest available';el('stockDataCard').innerHTML=`<strong>${data.name||data.symbol} (${data.symbol})</strong><p>${data.source} quote as of ${asOf}. ${data.exchange||''} ${data.industry?`- ${data.industry}`:''}</p><div class="spec-grid"><div><span>Price</span><b>${formatMaybe(data.price)}</b></div><div><span>Market cap</span><b>${formatMaybe(data.marketCap,compactDollars)}</b></div><div><span>Shares out.</span><b>${data.sharesOutstanding?`${Number(data.sharesOutstanding).toFixed(0)}M`:'N/A'}</b></div><div><span>EPS TTM</span><b>${formatMaybe(data.eps)}</b></div><div><span>P/E</span><b>${data.peTtm?Number(data.peTtm).toFixed(1):'N/A'}</b></div><div><span>52W range</span><b>${formatMaybe(data.week52Low)} - ${formatMaybe(data.week52High)}</b></div></div>`}
function applyStockDataToProjection(data){el('ticker').value=data.symbol;if(data.price)el('currentPrice').value=Number(data.price).toFixed(2);if(data.revenueTtm)el('revenue').value=Math.round(Number(data.revenueTtm));if(data.sharesOutstanding)el('shares').value=Math.round(Number(data.sharesOutstanding));if(data.eps)el('eps').value=Number(data.eps).toFixed(2);if(data.netMargin&&Number.isFinite(Number(data.netMargin))){const m=Math.max(0,Number(data.netMargin));el('bearMargin').value=Math.max(1,m*.72).toFixed(1);el('baseMargin').value=m.toFixed(1);el('bullMargin').value=(m*1.18).toFixed(1)}if(data.peTtm&&Number.isFinite(Number(data.peTtm))){const p=Math.max(1,Number(data.peTtm));el('bearPe').value=Math.max(5,p*.7).toFixed(1);el('basePe').value=p.toFixed(1);el('bullPe').value=(p*1.25).toFixed(1)}renderStockDataCard(data);setDataStatus(`${data.source} live`);runProjection()}
async function fetchProjectionTicker(){const b=el('fetchTicker');b.disabled=true;b.textContent='Fetching...';setDataStatus('Fetching data');try{applyStockDataToProjection(await fetchStockData(el('ticker').value))}catch(e){setDataStatus('Data unavailable');el('stockDataCard').innerHTML=`<strong>Could not load data.</strong><p>${e.message}</p>`}finally{b.disabled=false;b.textContent='Fetch live data'}}
function drawLineChart(canvas,series,field){const ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height,pad=46;ctx.clearRect(0,0,w,h);ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h);const all=series.flatMap(i=>i.yearly.map(p=>p[field])),max=Math.max(...all,1)*1.12,years=series[0]?.yearly.length-1||1;ctx.strokeStyle='#dbe3de';ctx.lineWidth=1;ctx.font='13px Inter, sans-serif';ctx.fillStyle='#607069';for(let i=0;i<=4;i++){const y=pad+((h-pad*2)*i)/4;ctx.beginPath();ctx.moveTo(pad,y);ctx.lineTo(w-pad,y);ctx.stroke();ctx.fillText(dollars.format(max*(1-i/4)),8,y+4)}series.forEach(item=>{ctx.strokeStyle=item.color;ctx.lineWidth=3;ctx.beginPath();item.yearly.forEach((point,index)=>{const x=pad+((w-pad*2)*point.year)/years,y=h-pad-((h-pad*2)*point[field])/max;if(index===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)});ctx.stroke();const last=item.yearly[item.yearly.length-1],y=h-pad-((h-pad*2)*last[field])/max;ctx.fillStyle=item.color;ctx.fillText(item.label,Math.min(w-pad+8,w-42),y+4)});ctx.fillStyle='#607069';ctx.fillText('Today',pad,h-14);ctx.fillText(`Year ${years}`,w-pad-44,h-14)}
function runProjection(){const r=calculateProjection(readProjectionInputs());renderProjection(r);return r}
function runCompare(){const years=Math.max(1,Math.min(15,numberValue('compareYears'))),stocks=['A','B'].map((slot,index)=>{const ticker=el(`compare${slot}Ticker`).value.trim().toUpperCase()||`STOCK ${slot}`,price=Number(el(`compare${slot}Price`).value)||0,eps=Number(el(`compare${slot}Eps`).value)||0,growth=(Number(el(`compare${slot}Growth`).value)||0)/100,pe=Number(el(`compare${slot}Pe`).value)||0,yearly=[];for(let year=0;year<=years;year++)yearly.push({year,price:eps*Math.pow(1+growth,year)*pe});const terminal=yearly[yearly.length-1].price,cagr=price>0?Math.pow(terminal/price,1/years)-1:0;return{key:slot,label:ticker,color:index===0?'#356aa8':'#0e7a5f',yearly,terminal,cagr,returnMultiple:price>0?terminal/price:0}});el('compareCards').innerHTML=stocks.map(s=>`<article class="metric-card"><span>${s.label}</span><strong>${dollars.format(s.terminal)}</strong><p>${pct.format(s.cagr)} annualized, ${s.returnMultiple.toFixed(2)}x return</p></article>`).join('');drawLineChart(el('compareChart'),stocks,'price')}
async function fetchCompareTickers(){const b=el('fetchCompare');b.disabled=true;b.textContent='Fetching...';try{const[a,c]=await Promise.all([fetchStockData(el('compareATicker').value),fetchStockData(el('compareBTicker').value)]);if(a.price)el('compareAPrice').value=Number(a.price).toFixed(2);if(a.eps)el('compareAEps').value=Number(a.eps).toFixed(2);if(a.peTtm)el('compareAPe').value=Number(a.peTtm).toFixed(1);if(c.price)el('compareBPrice').value=Number(c.price).toFixed(2);if(c.eps)el('compareBEps').value=Number(c.eps).toFixed(2);if(c.peTtm)el('compareBPe').value=Number(c.peTtm).toFixed(1);setDataStatus(`${a.source} live`);runCompare()}catch(e){setDataStatus('Compare fetch failed');alert(e.message)}finally{b.disabled=false;b.textContent='Fetch A & B'}}
function saveProjection(){const r=lastProjection||runProjection(),base=r.cases.find(i=>i.key==='base'),saved=JSON.parse(localStorage.getItem('stockLabWatchlist')||'[]');saved.unshift({ticker:r.input.ticker,date:new Date().toLocaleDateString(),currentPrice:r.input.currentPrice,bear:r.cases[0].terminal.price,base:base.terminal.price,bull:r.cases[2].terminal.price,cagr:base.cagr});localStorage.setItem('stockLabWatchlist',JSON.stringify(saved.slice(0,24)));renderWatchlist()}
function renderWatchlist(){const saved=JSON.parse(localStorage.getItem('stockLabWatchlist')||'[]');el('watchlistGrid').innerHTML=saved.map(i=>`<article class="watch-card"><h3>${i.ticker}</h3><p class="small-muted">Saved ${i.date} from ${dollars.format(i.currentPrice)}</p><dl><div><dt>Bear</dt><dd>${dollars.format(i.bear)}</dd></div><div><dt>Base</dt><dd>${dollars.format(i.base)}</dd></div><div><dt>Bull</dt><dd>${dollars.format(i.bull)}</dd></div><div><dt>Base CAGR</dt><dd>${pct.format(i.cagr)}</dd></div></dl></article>`).join('')||'<p class="small-muted">No saved projections yet.</p>'}
function runReverse(){const price=numberValue('revPrice'),eps=numberValue('revEps'),pe=numberValue('revPe'),years=Math.max(1,numberValue('revYears')),growth=eps>0?Math.pow((pe>0?price/pe:0)/eps,1/years)-1:0;el('reverseAnswer').innerHTML=`<strong>${pct.format(growth)}</strong>annual EPS growth is implied by today's price at the selected exit multiple.`}
function runMos(){const fairValue=numberValue('fairValue'),currentPrice=numberValue('mosPrice'),safety=numberValue('mosPercent')/100,buyBelow=fairValue*(1-safety),upside=currentPrice>0?fairValue/currentPrice-1:0;el('mosAnswer').innerHTML=`<strong>${dollars.format(buyBelow)}</strong>buy zone with ${pct.format(upside)} upside to fair value.`}
function runSize(){const portfolio=numberValue('portfolioValue'),risk=numberValue('riskPercent')/100,entry=numberValue('entryPrice'),stop=numberValue('stopPrice'),dollarsAtRisk=portfolio*risk,perShareRisk=Math.max(entry-stop,0),shares=perShareRisk>0?Math.floor(dollarsAtRisk/perShareRisk):0;el('sizeAnswer').innerHTML=`<strong>${shares.toLocaleString()} shares</strong>${dollars.format(shares*entry)} position size, risking ${dollars.format(dollarsAtRisk)}.`}
function bindEvents(){document.querySelectorAll('.tab').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));document.querySelectorAll('.panel').forEach(p=>p.classList.remove('active'));button.classList.add('active');el(button.dataset.tab).classList.add('active')}));el('projectionForm').addEventListener('submit',e=>{e.preventDefault();runProjection()});fields.forEach(f=>el(f).addEventListener('input',runProjection));el('loadSample').addEventListener('click',()=>{Object.entries(sample).forEach(([k,v])=>el(k).value=v);runProjection()});el('saveProjection').addEventListener('click',saveProjection);el('fetchTicker').addEventListener('click',fetchProjectionTicker);el('runCompare').addEventListener('click',runCompare);el('fetchCompare').addEventListener('click',fetchCompareTickers);el('runReverse').addEventListener('click',runReverse);el('runMos').addEventListener('click',runMos);el('runSize').addEventListener('click',runSize);el('clearWatchlist').addEventListener('click',()=>{localStorage.removeItem('stockLabWatchlist');renderWatchlist()});el('saveNotes').addEventListener('click',()=>localStorage.setItem('stockLabNotes',el('researchNotes').value));el('useCurrentForA').addEventListener('click',()=>{const input=readProjectionInputs();el('compareATicker').value=input.ticker;el('compareAPrice').value=input.currentPrice;el('compareAEps').value=input.eps;el('compareAGrowth').value=(input.cases.base.growth*100).toFixed(1);el('compareAPe').value=input.cases.base.pe;runCompare()})}
function init(){el('currentDate').textContent=new Date().toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric',year:'numeric'});el('researchNotes').value=localStorage.getItem('stockLabNotes')||'';bindEvents();runProjection();runCompare();runReverse();runMos();runSize();renderWatchlist()}init();
